services:
    mysql:
        container_name: ${APP_NAME}-mysql
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
        ports:
            - 3306:3306
    php:
        container_name: ${APP_NAME}-php
        build: 
            context: ./docker/php
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/html/
        entrypoint:
            sleep infinity
